name: code_editor
description: "A simple minimalist code editor"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  material: ^1.0.0+2
  font_awesome_flutter: ^10.7.0
  simple_icons: ^10.1.3
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  file_picker: ^8.0.0+1
  path: ^1.9.0
  restart_app: ^1.2.1
  path_provider: ^2.1.2
  flutter_code_editor: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/settings/

  fonts:
    - family: "Jetbrains Mono"
      fonts:
        - asset: lib/assets/fonts/JetBrains_Mono/static/JetBrainsMono-Regular.ttf

    - family: "Noto Sans"
      fonts:
        - asset: lib/assets/fonts/Noto_Sans/NotoSans-VariableFont_wdth.ttf